let div = document.createElement('div');
let textNode = document.createTextNode('Глупая шутка про табуретку');
document.body.append(div);
div.append(textNode);
div.classList.add('goose');
let goose = document.querySelector('.goose');
goose.style.margin = "50px";
let ol = document.createElement('ol');
document.body.append(ol);
let li = document.createElement('li');
ol.append(li);
let Shutka = document.createTextNode('Заходят как то негр, фемка, фашист в бар. Бармен им говорит: у меня всего 3 патрона в дробовике, и 3 раза стреляет в негра.');
li.append(Shutka);
let li2 = document.createElement('li');
ol.append(li2);
let horr = document.createTextNode('Идёт Штирлец по тропинке и падает в яму, еле как выбирается, "Чудес не бывает" поумал штирлец и прыгнул обратно в яму.');
li2.append(horr);
let li3 = document.createElement('li');
ol.append(li3);
let apopp = document.createTextNode('Стоят как то на остановке 2 пьяных мужика, один другому говорит: "Закурить нету?". Второй достаёт из кармана зажигалку, а она по всей руке потекла. Поджигает и вся рука загоряется. Первый мужик подкуривает, втягивается и говорит: "ну ты бл* фокусник."');
li3.append(apopp);